---
title: "Wildlife Density Estimation With ct R Package Using Distance Sampling"
bibliography: distance_sampling.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Introduction

Estimating animal density (number of individuals per unit of area) is not just a technical exercise—it is a necessity for wildlife monitoring and conservation. Reliable density estimates help answer key ecological and management questions such as: **How many animals live in a given conservation area?** **How many individuals are expected per unit of area?** **How does density or abundance vary in relation to environmental factors** such as habitat type, elevation, climate, or proximity to human settlements?

Insights from density estimation are fundamental for detecting population trends (increasing or declining), identifying ecological drivers, and guiding conservation strategies. Without such tools, it is nearly impossible to measure the effectiveness of management actions or to plan interventions for species of concern.

A variety of methods have been developed to estimate animal density from field data. These include Spatially Explicit Capture–Recapture (SECR), Distance Sampling (DS), Random Encounter Models (REM), Time-to-Event (TTE) and Space-to-Event (STE) approaches, Spatial Mark–Resight, and Spatial Partial Identity methods, among others. Each method has its own assumptions, strengths, and limitations. A useful overview and comparison is provided by [@Clarke2023], which can serve as an entry point for choosing the right approach.

In this article, we focus on **distance sampling** as applied to camera trap data using the **ct R package**. While it is not possible to cover the full scope of distance sampling theory, we highlight key concepts needed to avoid common misunderstandings and to build a clear picture of how the method works in practice [here](https://stangandaho.github.io/ct/articles/distance_sampling_guide.html). For readers who wish to dive deeper into the theory and applications, the classic reference by [@Buckland2015] remains highly recommended.


## Data Preparation
Please come back later 👨💻 ...


## Reference
