# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stack_list <- function(df_list) {
    .Call('_ct_stack_list', PACKAGE = 'ct', df_list)
}

